/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogin;

import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Visuales
 */
public class VentanaListaDePacientes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListaDePacientes
     */
    DefaultTableModel modelo;

    public VentanaListaDePacientes() {
        initComponents();;
        String[] cab = {"nombre", "horas", "minutos", "descripcion_atencion", "persona_rut", "id_pago"};//Se crea la cabezera
        String[][] datos = {};
        modelo = new DefaultTableModel(datos, cab) {//Se crea el modelo, bloqueando las filas editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        //Se carga el modelo
        tbPacienteAtendido.setModel(clases.FuncionesPaciente.cargarTabla(clases.FuncionesGenerales.getRut(), clases.FuncionesGenerales.getId(), modelo));
        //Se agrega a la tabla una evento que reconozca el Mouse
        tbPacienteAtendido.addMouseListener(new MouseAdapter() {
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPacienteAtendido = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lista de pacientes");

        tbPacienteAtendido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Paciente", "Nombre", "Hora"
            }
        ));
        tbPacienteAtendido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPacienteAtendidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPacienteAtendido);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("* Doble click sobre un elemento de la tabla para modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 542, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPacienteAtendidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPacienteAtendidoMouseClicked
        if (evt.getClickCount() == 2) {//Si se dan dos clicks a un elemento seleccionado, se executa la siguiente accion
            int row = tbPacienteAtendido.rowAtPoint(evt.getPoint());//Se obtiene la fila
            try {
                if (tbPacienteAtendido.getValueAt(row, 3).toString().equals("Espera")) {
                    int opcion = JOptionPane.showConfirmDialog(this, "Seguro desea modificar ha este paciente", "¿Modificar?", JOptionPane.YES_NO_OPTION);//Se pregunta si se quieren modificar los datos
                    if (opcion == JOptionPane.YES_OPTION) {//Si se clickea "Si", se executara la siguiente accion
                        if ((clases.FuncionesMedico.pacienteAtendido(Integer.parseInt(tbPacienteAtendido.getValueAt(row, 5).toString())))) {//Si se satisface la funcon, se obtendra un mensaje y se cargara nuevamente la tabla
                            JOptionPane.showMessageDialog(this, "modificado correctamente");
                            clases.FuncionesPaciente.cargarTabla(clases.FuncionesGenerales.getRut(), clases.FuncionesGenerales.getId(), modelo);
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo guardar");//Sino, se obtendra el siguiente mensaje
                        }
                    }
                } else{
                    JOptionPane.showMessageDialog(this, "No se puede actualizar un paciente con el estado '"+tbPacienteAtendido.getValueAt(row, 3).toString()+"'");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error." + e.getMessage());
            }
        }
    }//GEN-LAST:event_tbPacienteAtendidoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Acceso().setVisible(true);//Si se devuelve, se regresa a la ventana anterior y se cierra esta.
    }//GEN-LAST:event_jButton1ActionPerformed
    //Cuando se cierra la ventana...
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        clases.FuncionesGenerales.setId(null);//Se eliminan la id y rut ingresado de la ventana Acceso
        clases.FuncionesGenerales.setRut(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListaDePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListaDePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListaDePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListaDePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VentanaListaDePacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPacienteAtendido;
    // End of variables declaration//GEN-END:variables
}
