/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogin;

import java.awt.event.MouseAdapter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.datacontract.schemas._2004._07.backend.ArrayOfReserva;
import javax.swing.JOptionPane;
/**
 *
 * @author raide
 */
public class VentanaTablaReservaPorCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTablaReservaPorCliente
     */
    DefaultTableModel modelo;
    public VentanaTablaReservaPorCliente() {
        initComponents();
        String[] cab = {"nombre", "rut", "fecha de atencion", "descripcion", "id_agenda", "id_medico"};//La cebezera de la tabla
        String[][] datos = {};
        modelo = new DefaultTableModel(datos, cab) {//Se ingresa los datos al nuevo modelo ingresado, y se bloquean las filas editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbHorasReservadas.setModel(modelo);//Se inserta el modelo creado anteriormente a la tabla de la ventana
        tbHorasReservadas.addMouseListener(new MouseAdapter() {//Se inserta un evento a la tabla que reconozca el Mouse
        });
        for (org.datacontract.schemas._2004._07.backend.PacienteNoPago dato : clases.FuncionesPaciente.listadoPacienteNoPago().getPacienteNoPago()) {//Se cargaran las reservas a la tabla
            Object[] elementos = {dato.getNombre().getValue(), dato.getRutPaciente().getValue(), dato.getFechaReserva().getDay()+"/"+dato.getFechaReserva().getMonth()+"/"+dato.getFechaReserva().getYear(), dato.getDescripcion().getValue() , dato.getIdAgenda(), dato.getIdMedico()};
            modelo.addRow(elementos);
        }
        
        TableColumnModel tcm = tbHorasReservadas.getColumnModel();//Se obtienen las columnas de la tabla
        tcm.removeColumn(tcm.getColumn(5));//Se elimina la columna con el indice 5(id_medico)
        tcm.removeColumn(tcm.getColumn(4));//Se elimina la columna con el indice 4(id_agenda)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHorasReservadas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Horas reservadas");

        tbHorasReservadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHorasReservadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHorasReservadasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHorasReservadas);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbHorasReservadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHorasReservadasMouseClicked
        if (evt.getClickCount() == 2) {//Si se dan dos click aun elemento de la tabla, se executaran las siguientes acciones...
            int row = tbHorasReservadas.rowAtPoint(evt.getPoint());//Se obtiene la fila seleccionada
            try {
                String rut = tbHorasReservadas.getValueAt(row, 1).toString();//Se obtiene el rut de la fila..
                String id_agenda = tbHorasReservadas.getModel().getValueAt(row, 4).toString();//Se obtiene el id_agenda de la tabla..
                String id_medico = tbHorasReservadas.getModel().getValueAt(row, 5).toString();//Se obtiene el id_medico de la tabla..
                VentanaPago vp = new VentanaPago(rut, id_medico, id_agenda);
                vp.setVisible(true);//Se visualizara VentanaPago y se cierra esta ventana
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: "+ e.getMessage());
            }
        }
    }//GEN-LAST:event_tbHorasReservadasMouseClicked
     //Si se clickea salir, se elimina la lista obtenida anteiormente, y vuelve a la ventana anterior
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Acceso().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaReservaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaReservaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaReservaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaReservaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTablaReservaPorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHorasReservadas;
    // End of variables declaration//GEN-END:variables
}
